services:

# Order of Items on each service
# Host:Container

# image
# container_name
# hostname
# restart
# environment
# labels
# volumes
# ports
# env

#####################################
# ____                              #
#/ ___|  ___  _ __   __ _ _ __ _ __ #
#\___ \ / _ \| '_ \ / _` | '__| '__|#
# ___) | (_) | | | | (_| | |  | |   #
#|____/ \___/|_| |_|\__,_|_|  |_|   #                                  
#####################################

  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    environment:
      - DOCKER_MODS=${THEMESONARR}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - $INSTALLDIR/mediarr/sonarr:/config
      - $HOSTDATA:$CONTAINERDATA
    ports:
      - 8989:8989
    env_file:
      - '.env'

####################################
# ____           _                 #
#|  _ \ __ _  __| | __ _ _ __ _ __ #
#| |_) / _` |/ _` |/ _` | '__| '__|#
#|  _ < (_| | (_| | (_| | |  | |   #
#|_| \_\__,_|\__,_|\__,_|_|  |_|   #
####################################

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    environment:
      - DOCKER_MODS=${THEMERADARR}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - $INSTALLDIR/mediarr/radarr:/config
      - $HOSTDATA:$CONTAINERDATA
    ports:
      - 7878:7878
    env_file:
      - '.env'

######################################################
#       _     _ _   _                            _   #
#  __ _| |__ (_) |_| |_ ___  _ __ _ __ ___ _ __ | |_ #
# / _` | '_ \| | __| __/ _ \| '__| '__/ _ \ '_ \| __|#
#| (_| | |_) | | |_| || (_) | |  | | |  __/ | | | |_ #
# \__, |_.__/|_|\__|\__\___/|_|  |_|  \___|_| |_|\__|#
#    |_|                                             #
######################################################

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - $INSTALLDIR/mediarr/qbittorrent:/config
      - $HOSTDATA:$CONTAINERDATA
    ports:
      - 2081:2081
      - 6059:6059
      - 6059:6059/udp
    healthcheck:
      start_period: 15s
    env_file:
      - '.env'

#############################################
# ____                    _                 #
#|  _ \ _ __ _____      _| | __ _ _ __ _ __ #
#| |_) | '__/ _ \ \ /\ / / |/ _` | '__| '__|#
#|  __/| | | (_) \ V  V /| | (_| | |  | |   #
#|_|   |_|  \___/ \_/\_/ |_|\__,_|_|  |_|   #
#############################################

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - DOCKER_MODS=${THEMEPROWLARR}
    volumes:
      - $INSTALLDIR/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    env_file:
      - '.env'

###########################################################
# _____ _                           _                     #
#|  ___| | __ _ _ __ ___  ___  ___ | |_   _____ _ __ _ __ #
#| |_  | |/ _` | '__/ _ \/ __|/ _ \| \ \ / / _ \ '__| '__|#
#|  _| | | (_| | | |  __/\__ \ (_) | |\ V /  __/ |  | |   #
#|_|   |_|\__,_|_|  \___||___/\___/|_| \_/ \___|_|  |_|   #
###########################################################

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    restart: unless-stopped
    ports:
      - 8191:8191
    env_file:
      - '.env'

#####################
#       _           #
# _ __ | | _____  __#
#| '_ \| |/ _ \ \/ /#
#| |_) | |  __/>  < #
#| .__/|_|\___/_/\_\#
#|_|                #
#####################

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - VERSION=${PLEXVERSION}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - $INSTALLDIR/mediarr/plex:/config
      - $HOSTDATA:$CONTAINERDATA
    env_file:
      - '.env'

##################################
# _              _         _ _ _ #
#| |_ __ _ _   _| |_ _   _| | (_)#
#| __/ _` | | | | __| | | | | | |#
#| || (_| | |_| | |_| |_| | | | |#
# \__\__,_|\__,_|\__|\__,_|_|_|_|#
##################################

  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    restart: unless-stopped
    volumes:
      - $INSTALLDIR/mediarr/tautulli:/config
    ports:
      - 8181:8181
    env_file:
      - '.env'

networks:
  default:
    name: mediarr
    enable_ipv6: true # Optional
# Very optional, only use this if you want to change the network ip inside the docker stack
# Not really needed, i just added to organize my docker install
    ipam:
      config:
        - subnet: 192.168.10.0/24 #IPV4 NETWORK
        - subnet: 2001:db8:2::/64 #IPV6 NETWORK